import { type NextPage } from "next";
import Head from "next/head";
import { BiAnalyse } from "react-icons/bi";
import { motion } from "framer-motion";

const Home: NextPage = () => {
  return (
    <motion.div
      initial={{ y: "10%", opacity: 0.1, scale: 1 }}
      animate={{ y: 0, opacity: 1, scale: 1 }}
      transition={{ duration: 0.5, ease: "easeIn" }}
      exit={{ opacity: 0 }}
    >
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        
        <div className="grid items-start justify-center gap-8">
          <div className="group relative">
            <div className="absolute -inset-0.5 rounded-lg bg-gradient-to-r from-pink-600 to-purple-600 opacity-75 blur transition duration-1000 group-hover:opacity-100 group-hover:duration-200"></div>
            <button className="relative flex items-center space-x-5 divide-x divide-gray-600 rounded-lg bg-black px-7 py-5 text-5xl leading-none">
              <BiAnalyse className="inline animate-spin-slow text-pink-600" />
              <span className="text-gray-100 font-mono font-bold">Moodify</span>
            </button>
          </div>
        </div>

      </main>
    </motion.div>
  );
};

export default Home;
